import json
from pathlib import Path
Path("tmp/samples").mkdir(parents=True, exist_ok=True)

configfile: "config.yaml"

# Get app
get_fake_data =  config["app"]["get_fake_data"]
create_db = config["app"]["create_db"]
effect_detector = config["app"]["effect_detector"]
get_report = config["app"]["get_report"]

rule all:  
    input:
        config["config"]["output_path"]
        
rule fake_data_creation:
    params:
        num_sample = config["config"]["num_sample"],
        num_rep = config["config"]["num_rep"]
    output:
        expand("tmp/samples/{sample}/{sample}.tsv", sample = [f"sample{i+1}" for i in range(config["config"]["num_sample"])])
    script:
        "scripts/fake_data_creator.py"
        
rule ancova_stats:
    input:
        "tmp/samples/{sample}/{sample}.tsv"
    params:
        sample_id = "{sample}",
        p_ph_covar = config["config"]["p_ph_covar"]
    output:
        "tmp/samples/{sample}/sqlite.db"
    threads:
        4
    shell:
        "{create_db} -db {output} && "
        "{effect_detector} -id {params.sample_id} -i {input} -p {params.p_ph_covar} -db {output}"

rule get_report:
    input:
        dbs = expand("tmp/samples/{sample}/sqlite.db", sample = [f"sample{i+1}" for i in range(config["config"]["num_sample"])])
    output:
        config["config"]["output_path"]
    script:
        "scripts/get_report.py"

              